apiVersion: apps/v1beta1 # for versions before 1.6.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: app1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: app1
        friend: app2
    spec:
      containers:
      - name: frontend
        image: nginx
      nodeSelector:
        key: value
