apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "7"
  creationTimestamp: 2017-09-11T22:43:00Z
  generation: 26
  labels:
    run: host-id
  name: host-id-test
  namespace: default
  resourceVersion: "456249"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/host-id
  uid: 9060fd9b-9742-11e7-bce5-42010a80027c
spec:
  replicas: 3
  selector:
    matchLabels:
      run: host-id
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: host-id
    spec:
      containers:
      - env:
        - name: LOG_SOURCE_IP
          valueFrom:
            configMapKeyRef:
              key: log.source_ip
              name: host-id-config
        image: iftachsc/host-id:latest
        imagePullPolicy: Always
        name: host-id
        ports:
        - containerPort: 3000
          protocol: TCP
        resources:
          limits:
            cpu: "2.5"
            memory: 2.5Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
