apiVersion: certificates.k8s.io/v1beta1
kind: CertificateSigningRequest
metadata:
  name: user-request-jlanister
spec:
  groups:
  - system:authenticated
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1dUQ0NBVUVDQVFBd0ZERVNNQkFHQTFVRUF4TUphbXhoYm1semRHVnlNSUlCSWpBTkJna3Foa2lHOXcwQgpBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUFvNjZ5MW5RbjNKd1Ixb0ttQTcyc3lIUVVHYTFhT3NxRmRvZG1tbWpMCkpDMFdqcWJKS3lpcjRXdlhBYW10ZTZjVmprdjRDY01mK1VoeWJmSTNZNHpMNDQ3SHduamszd3JVazRzR2dZOUwKdVdkcTBla0ZYdzlQL21pZGhVc2hkeGhzSlZSc3JFWXZxWnk2VENWZmZ2S29kazg4KzVRTURDUmsyUVZHeE1UQwp3dnpwNk9jSnFjeDVySTRPZkZuWnZLR010OWhpbHErdDhJNiszRlpuNndsdFhrK2QxUGZCczB2Qlp4RC9UdmNyCllab01RS2lBeDBQSGRFTjdzS3UvUGZTYXBub1l1bnlaSnlmK2dIdHAxWGpVU2dKelJNcWNLQmFTeWZvZE1BaXAKYkZ2cm55ODRsM3RVWWljeFNwQy84NW9jMUN4ZXhjYzlTV0tzeTFpNHBrVm1Pd0lEQVFBQm9BQXdEUVlKS29aSQpodmNOQVFFRkJRQURnZ0VCQURpY296WHJ2WDY5QjZDWVdYU2JxbzRiQktwL1hrbE43UXgydXdVZ3BpcE1POW56CkRueEgxTk5ZeGU5SUtoaVZudVJwUjdTZmJIM0JGS2pocHFsUTRhejl3bHRPcVBEUGVTZjltMkNOTE5mMml0UUkKcUpzd0NuSGFmcXlybE0wRXhLNy9TRUJ5SExqNEhGU1MycEtXSW83KzNCOVlhRFhIWHZ1U1RSbkFXVnRUbXZqQQpBMy9CQ3BudDFvNktQS0VsRWltTmlLVkVHVEgzd0FsU1pEY0FVelRJUEk3Tmc2NEZZZUlCbXNsdjVEYUJyT2JnClErdGtlbXNWT1ZyckV2dkVtV3dLUUovZ1l4SzkzQ3ZHV2d4d0ptNkFHUDFqWnhBaGM4Nll4cUR3L3NMRWtTeVAKRVNOWlJYREwxM29meE40aW5JcWl1QUNKZUpIUlUyUS9IbTNweGZVPQotLS0tLUVORCBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0K
  username: jlanister
  usages:
  - digital signature
  - key encipherment
  - client auth
