apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hostid-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: www.myfuckingapp.com
    http:
      paths:
      - backend:
          serviceName: <serviceName>
          servicePort: <servicePort>
        path: / 
