---
# Source: nginx-ingress/templates/controller-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: nginx-ingress
    chart: nginx-ingress-1.3.0
    component: "controller"
    heritage: Tiller
    release: my
  name: my-nginx-ingress-controller
data:
  enable-vts-status: "false"
